# Generated by Django 3.0.8 on 2020-09-09 04:07

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp1', '0002_auto_20200906_1146'),
    ]

    operations = [
        migrations.AlterField(
            model_name='topic',
            name='topic_name',
            field=models.CharField(max_length=100, unique=True, validators=[django.core.validators.MaxLengthValidator(10)]),
        ),
    ]
